services:
  state-processor:
    build:
      context: ./ems/state-processor
      args:
        PORT: 5002
    ports:
      - "5002:5002"
    env_file: .env
    environment:
      FLASK_APP: app.main:app
    restart: always

  db-writer:
    build:
      context: ./ems/db-writer
      args:
        PORT: 5005
    ports:
      - "5005:5005"
    env_file: .env
    environment:
      FLASK_APP: app.main:app
    restart: always
