services:
  control:
    build:
      context: ./control
      args:
        PORT: 5003
    ports:
      - "5003:5003"
    env_file: .env
    restart: always

  ai-service:
    build:
      context: ./ai-service
      args:
        PORT: 5004
    ports:
      - "5004:5004"
    env_file: .env
    restart: always
