services:
  ingestion:
    build:
      context: ./ems/ingestion
      args:
        PORT: 5001
    ports:
      - "5001:5001"
    env_file: .env
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      mqtt:
        condition: service_started

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
        --appendonly yes
        --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "REDISCLI_AUTH=$${REDIS_PASSWORD} redis-cli ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  mqtt:
    image: eclipse-mosquitto:2.0.18
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    entrypoint: ["/bin/sh", "/mosquitto/config/entrypoint.sh"]
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./infra/mosquitto/acl.template:/mosquitto/config/acl.template:ro
      - ./infra/mosquitto/entrypoint.sh:/mosquitto/config/entrypoint.sh:ro
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log

volumes:
  redis_data:
  mqtt_data:
  mqtt_log:
